'use client';
import { useEffect, useMemo, useState } from 'react';
import { Loader2, RotateCcw, Search, ShieldCheck, X, AlertTriangle } from 'lucide-react';
import toast from 'react-hot-toast';
import { rbacService, PermissionMap, RbacCatalog } from '@/lib/services/rbacService';

interface StaffUser { _id: string; name: string; role: string; permissions?: PermissionMap; }
export default function PermissionManager({ user, onClose, onSaved }: { user: StaffUser; onClose: () => void; onSaved: () => void }) {
  const [catalog, setCatalog] = useState<RbacCatalog | null>(null); const [permissions, setPermissions] = useState<PermissionMap>({}); const [search, setSearch] = useState(''); const [saving, setSaving] = useState(false); const [showResetConfirm, setShowResetConfirm] = useState(false); const [resetting, setResetting] = useState(false);
  useEffect(() => { rbacService.getCatalog().then(response => { setCatalog(response.data); setPermissions({ ...(response.data.roles.find(item => item.id === user.role)?.permissions || {}), ...(user.permissions || {}) }); }).catch(() => toast.error('Unable to load permission catalog')); }, [user]);
  const modules = useMemo(() => Object.entries(catalog?.modules || {}).filter(([, label]) => label.toLowerCase().includes(search.toLowerCase())), [catalog, search]);
  const setModule = (module: string, value: boolean) => setPermissions(current => ({ ...current, ...Object.fromEntries((catalog?.moduleActions[module] || []).map(action => [`${module}.${action}`, value])) }));
  const save = async () => { setSaving(true); try { const token = localStorage.getItem('authToken'); const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5001/api'}/users/${user._id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ permissions }) }); const data = await response.json(); if (!data.success) throw new Error(data.error); toast.success('Permissions saved successfully'); onSaved(); onClose(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Failed to save permissions'); } finally { setSaving(false); } };
  const handleReset = async () => { setResetting(true); try { await rbacService.resetPermissions(user._id); toast.success('Permissions reset to role defaults'); onSaved(); onClose(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Failed to reset permissions'); } finally { setResetting(false); setShowResetConfirm(false); } };
  if (!catalog) return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-secondary-900/50"><Loader2 className="h-7 w-7 animate-spin text-white" /></div>;
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-secondary-900/50 p-4" role="dialog" aria-modal="true" aria-labelledby="permission-title"><div className="flex max-h-[90vh] w-full max-w-6xl flex-col overflow-hidden rounded-xl bg-white shadow-2xl">
    <div className="flex items-start justify-between border-b border-secondary-200 px-6 py-4"><div><h2 id="permission-title" className="text-lg font-bold text-secondary-900">Manage permissions</h2><p className="mt-1 text-sm text-secondary-500">{user.name} · <span className="capitalize">{user.role}</span> defaults with user-specific overrides</p></div><button onClick={onClose} className="icon-button" aria-label="Close permission manager"><X className="h-5 w-5" /></button></div>
    <div className="flex flex-col gap-3 border-b border-secondary-200 bg-secondary-50 p-4 sm:flex-row sm:items-center"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-secondary-400" /><input value={search} onChange={event => setSearch(event.target.value)} className="input pl-9" placeholder="Search modules" /></label><button onClick={() => setPermissions(Object.fromEntries(Object.keys(permissions).map(key => [key, true])))} className="btn-secondary">Select all</button><button onClick={() => setPermissions(Object.fromEntries(Object.keys(permissions).map(key => [key, false])))} className="btn-secondary">Clear all</button><button onClick={() => setShowResetConfirm(true)} disabled={user.role === 'owner'} className="btn-secondary"><RotateCcw className="h-4 w-4" /> Reset to defaults</button></div>
    <div className="overflow-auto"><table className="w-full min-w-[900px]"><thead className="sticky top-0 z-10"><tr><th className="px-5 py-3 text-left">Module</th>{catalog.actions.map(action => <th key={action} className="px-3 py-3 text-center capitalize">{action}</th>)}<th className="px-3 py-3 text-center">All</th></tr></thead><tbody>{modules.map(([module, label]) => { const allowed = catalog.moduleActions[module] || []; return <tr key={module} className="border-t border-secondary-100"><td className="px-5 py-3 font-semibold text-secondary-800">{label}</td>{catalog.actions.map(action => { const key = `${module}.${action}`; return <td key={action} className="px-3 py-3 text-center">{allowed.includes(action) ? <input type="checkbox" checked={permissions[key] === true} onChange={event => setPermissions(current => ({ ...current, [key]: event.target.checked }))} aria-label={`${label} ${action}`} /> : <span className="text-secondary-300">—</span>}</td>; })}<td className="px-3 py-3 text-center"><input type="checkbox" checked={allowed.length > 0 && allowed.every(action => permissions[`${module}.${action}`])} onChange={event => setModule(module, event.target.checked)} aria-label={`Select all ${label} permissions`} /></td></tr>; })}</tbody></table></div>
    <div className="flex items-center justify-between border-t border-secondary-200 bg-white px-6 py-4"><p className="flex items-center gap-2 text-xs text-secondary-500"><ShieldCheck className="h-4 w-4 text-primary-700" />Changes are enforced by the API immediately.</p><div className="flex gap-2"><button onClick={onClose} className="btn-secondary">Cancel</button><button onClick={save} disabled={saving || user.role === 'owner'} className="btn-primary">{saving && <Loader2 className="h-4 w-4 animate-spin" />} Save permissions</button></div></div>
    {showResetConfirm && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/50 backdrop-blur-sm p-4"><div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden"><div className="bg-amber-50 border-b border-amber-200 px-6 py-4"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-amber-100 rounded-full flex items-center justify-center"><AlertTriangle className="h-5 w-5 text-amber-600" /></div><div><h3 className="text-lg font-bold text-secondary-900">Reset permissions to role defaults?</h3><p className="text-sm text-secondary-600 mt-1">This action cannot be undone.</p></div></div></div><div className="p-6"><p className="text-sm text-secondary-700 mb-4">This will remove all custom permission overrides for <strong>{user.name}</strong> and restore the default permissions for the <strong className="capitalize">{user.role}</strong> role.</p><div className="flex gap-3 justify-end"><button onClick={() => setShowResetConfirm(false)} disabled={resetting} className="btn-secondary">Cancel</button><button onClick={handleReset} disabled={resetting} className="btn-primary bg-amber-600 hover:bg-amber-700">{resetting && <Loader2 className="h-4 w-4 animate-spin mr-2" />} Reset permissions</button></div></div></div></div>}
  </div></div>;
}
